[tool.autopep8]
max_line_length = 100

[tool.black]
include = 'positron\/.*.py$|positron_language_server.py$|tests\/test_positron_.*.py$'
exclude = '''

(
  /(
    .data
    | .vscode
    | lib
  )/
)
'''
line-length = 100

[tool.isort]
profile = "black"

[tool.pyright]
exclude = ['lib']
extraPaths = ['lib/python', 'lib/jedilsp']
ignore = [
    # Ignore all pre-existing code with issues
    'get-pip.py',
    'install_debugpy.py',
    'normalizeSelection.py',
    'tensorboard_launcher.py',
    'testlauncher.py',
    'visualstudio_py_testlauncher.py',
    'testing_tools/unittest_discovery.py',
    'testing_tools/adapter/report.py',
    'testing_tools/adapter/util.py',
    'testing_tools/adapter/pytest/_discovery.py',
    'testing_tools/adapter/pytest/_pytest_item.py',
    'tests/debug_adapter/test_install_debugpy.py',
    'tests/unittestadapter/helpers.py',
    'tests/testing_tools/adapter/.data',
    'tests/testing_tools/adapter/test___main__.py',
    'tests/testing_tools/adapter/test_discovery.py',
    'tests/testing_tools/adapter/test_functional.py',
    'tests/testing_tools/adapter/test_report.py',
    'tests/testing_tools/adapter/test_util.py',
    'tests/testing_tools/adapter/pytest/test_cli.py',
    'tests/testing_tools/adapter/pytest/test_discovery.py',
    'tests/unittestadapter/.data/unittest_skip/unittest_skip_function.py'
]

[tool.ruff]
line-length = 140
ignore = ["E402"]
exclude = [
    # Ignore testing_tools files same as Pyright way
    'get-pip.py',
    'install_debugpy.py',
    'tensorboard_launcher.py',
    'testlauncher.py',
    'visualstudio_py_testlauncher.py',
    'testing_tools/unittest_discovery.py',
    'testing_tools/adapter/util.py',
    'testing_tools/adapter/pytest/_discovery.py',
    'testing_tools/adapter/pytest/_pytest_item.py',
    'tests/debug_adapter/test_install_debugpy.py',
    'tests/testing_tools/adapter/.data',
    'tests/testing_tools/adapter/test___main__.py',
    'tests/testing_tools/adapter/test_discovery.py',
    'tests/testing_tools/adapter/test_functional.py',
    'tests/testing_tools/adapter/test_report.py',
    'tests/testing_tools/adapter/test_util.py',
    'tests/testing_tools/adapter/pytest/test_cli.py',
    'tests/testing_tools/adapter/pytest/test_discovery.py',
    'pythonFiles/testing_tools/*',
    'pythonFiles/testing_tools/adapter/pytest/__init__.py',
    'pythonFiles/tests/pytestadapter/expected_execution_test_output.py',
    'pythonFiles/tests/unittestadapter/.data/discovery_error/file_one.py',
    'pythonFiles/tests/unittestadapter/test_utils.py',

]
