[package]
name = "echo"
version = "0.1.0"
edition = "2021"

[dependencies]
amalthea = { path = "../amalthea" }
log = "0.4.17"
env_logger = "0.10.0"
serde_json = "1.0.94"
async-trait = "0.1.66"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
