name: Assign DS issue to someone
on:
  issues:
    types: [opened, labeled]
jobs:
  assignIssue:
    name: Assign Issue to Someone
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/vscode-python'
    steps:
      - name: Created internally
        id: internal
        env:
            ISSUE_OWNER: ${{github.event.issue.owner.login}}
        run: |
          echo ::set-output name=result::$(node -p -e "['rchiodo', 'greazer', 'joyceerhl', 'DavidKutu', 'claudiaregio', 'IanMatthewHuff', 'DonJayamanne'].filter(item => process.env.ISSUE_OWNER.toLowerCase() === item.toLowerCase()).length > 0 ? 1 : 0")
        shell: bash
      - name: Should we proceed
        id: proceed
        env:
            ISSUE_LABELS: ${{toJson(github.event.issue.labels)}}
            ISSUE_ASSIGNEES: ${{toJson(github.event.issue.assignees)}}
            ISSUE_IS_INTERNAL: ${{steps.internal.outputs.result}}
        run: |
          echo ::set-output name=result::$(node -p -e "process.env.ISSUE_IS_INTERNAL === '0' && JSON.parse(process.env.ISSUE_ASSIGNEES).length === 0 && JSON.parse(process.env.ISSUE_LABELS).filter(item => item.name.indexOf('data science') >= 0).length === 1 && JSON.parse(process.env.ISSUE_LABELS).filter(item => item.name.indexOf('Epic') >= 0).length === 0 ? 1 : 0")
        shell: bash
      - uses: actions/checkout@v2
        if: steps.proceed.outputs.result == 1
      - name: Day of week
        if: steps.proceed.outputs.result == 1
        id: day
        run: |
          echo ::set-output name=number::$(node -p -e "new Date().getDay()")
        shell: bash
      - name: Hour of day
        if: steps.proceed.outputs.result == 1
        id: hour
        run: |
          echo ::set-output name=hour::$(node -p -e "(new Date().getUTCHours() - 7)%24")
        shell: bash
      - name: Week Number
        if: steps.proceed.outputs.result == 1
        id: week
        run: |
          echo ::set-output name=odd::$(node .github/workflows/week.js)
        shell: bash
      - name: Print day and week
        if: steps.proceed.outputs.result == 1
        run: |
          echo ${{steps.day.outputs.number}}
          echo ${{steps.week.outputs.odd}}
          echo ${{steps.hour.outputs.hour}}
        shell: bash
      - name: Even late friday (David)
        if: steps.proceed.outputs.result == 1 && steps.week.outputs.odd == 0 && steps.day.outputs.number == 5 && steps.hour.outputs.hour >= 16
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign DavidKutu
      - name: Odd late friday (Joyce)
        if: steps.proceed.outputs.result == 1 && steps.week.outputs.odd == 1 && steps.day.outputs.number == 5 && steps.hour.outputs.hour >= 16
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign joyceerhl
      - name: Even weekends (David)
        if: steps.proceed.outputs.result == 1 && steps.week.outputs.odd == 0 && (steps.day.outputs.number == 6 || steps.day.outputs.number == 0)
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign DavidKutu
      - name: Odd weekends (Joyce)
        if: steps.proceed.outputs.result == 1 && steps.week.outputs.odd == 1 && (steps.day.outputs.number == 6 || steps.day.outputs.number == 0)
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign joyceerhl
      - name: Odd Monday (David)
        if: steps.proceed.outputs.result == 1 && steps.week.outputs.odd == 1 && steps.day.outputs.number == 1 && steps.hour.outputs.hour < 16
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign DavidKutu
      - name: Even Monday (Joyce)
        if: steps.proceed.outputs.result == 1 && steps.week.outputs.odd == 0 && steps.day.outputs.number == 1 && steps.hour.outputs.hour < 16
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign joyceerhl
      - name: Tuesday (Ian)
        if: steps.proceed.outputs.result == 1 && (steps.day.outputs.number == 1 && steps.hour.outputs.hour >= 16) || (steps.day.outputs.number == 2 && steps.hour.outputs.hour < 16)
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign IanMatthewHuff
      - name: Wednesday (Rich)
        if: steps.proceed.outputs.result == 1 && (steps.day.outputs.number == 2 && steps.hour.outputs.hour >= 16) || (steps.day.outputs.number == 3 && steps.hour.outputs.hour < 16)
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign rchiodo
      - name: Thursday (Don)
        if: steps.proceed.outputs.result == 1 && (steps.day.outputs.number == 3 && steps.hour.outputs.hour >= 16) || (steps.day.outputs.number == 4 && steps.hour.outputs.hour < 16)
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign DonJayamanne
      - name: Friday (Claudia)
        if: steps.proceed.outputs.result == 1 && (steps.day.outputs.number == 4 && steps.hour.outputs.hour >= 16) || (steps.day.outputs.number == 5 && steps.hour.outputs.hour < 16)
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign claudiaregio
