name: Issue labels

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  # From https://github.com/marketplace/actions/github-script#apply-a-label-to-an-issue.
  add-classify-label:
    name: "Add 'classify'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const labels = result.map((label) => label.name)

            const skipClassify = ['needs community feedback', 'needs decision', 'needs PR', 'needs proposal', 'needs spike']

            if (!labels.includes(...skipClassify)) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['classify']
              })
            }
