name: 'Lock Issues'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  lock-issues:
    runs-on: ubuntu-latest
    steps:
      - name: 'Lock Issues'
        uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '30'
          process-only: 'issues'
          log-output: true
