name: PR files

on:
  pull_request:
    types:
      # On by default if you specify no types.
      - 'opened'
      - 'reopened'
      - 'synchronize'
      # For `skip-label` only.
      - 'labeled'
      - 'unlabeled'

jobs:
  changed-files-in-pr:
    name: 'Check for changed files'
    runs-on: ubuntu-latest
    steps:
      - name: 'package-lock.json matches package.json'
        uses: brettcannon/check-for-changed-files@v1.1.1
        with:
          prereq-pattern: 'package.json'
          file-pattern: 'package-lock.json'
          skip-label: 'skip package*.json'
          failure-message: '${prereq-pattern} was edited but ${file-pattern} was not (the ${skip-label} label can be used to pass this check)'

      - name: 'package.json matches package-lock.json'
        uses: brettcannon/check-for-changed-files@v1.1.1
        with:
          prereq-pattern: 'package-lock.json'
          file-pattern: 'package.json'
          skip-label: 'skip package*.json'
          failure-message: '${prereq-pattern} was edited but ${file-pattern} was not (the ${skip-label} label can be used to pass this check)'

      - name: 'Tests'
        uses: brettcannon/check-for-changed-files@v1.1.1
        with:
          prereq-pattern: src/**/*.ts
          file-pattern: |
            src/**/*.test.ts
            src/**/*.testvirtualenvs.ts
            .github/test_plan.md
          skip-label: 'skip tests'
          failure-message: 'TypeScript code was edited without also editing a ${file-pattern} file; see the Testing page in our wiki on testing guidelines (the ${skip-label} label can be used to pass this check)'
